[package]
name = "multitoken-io"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
gear-lib.workspace = true
primitive-types = { version = "0.12", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
scale-info = { version = "2", default-features = false }
gmeta.workspace = true
